const body = document.body, progress = document.getElementById('scrollProgress'), themeButton = document.getElementById('themeToggle'), menuButton = document.getElementById('menuToggle'), nav = document.getElementById('navLinks'); if (localStorage.getItem('portfolio-theme') === 'dark') body.classList.add('dark'); themeButton.addEventListener('click', () => { body.classList.toggle('dark'); localStorage.setItem('portfolio-theme', body.classList.contains('dark') ? 'dark' : 'light') }); menuButton.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuButton.setAttribute('aria-expanded', String(open)) }); nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { nav.classList.remove('open'); menuButton.setAttribute('aria-expanded', 'false') })); function updateProgress() { const max = document.documentElement.scrollHeight - innerHeight; progress.style.width = (max > 0 ? scrollY / max * 100 : 0) + '%' } window.addEventListener('scroll', updateProgress, { passive: true }); updateProgress(); const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target) } }), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); const filters = [...document.querySelectorAll('.filter-chip')], cards = [...document.querySelectorAll('.project-card')], count = document.getElementById('projectCount'); filters.forEach(button => button.addEventListener('click', () => { filters.forEach(item => item.classList.toggle('active', item === button)); const selected = button.dataset.filter; let shown = 0; cards.forEach(card => { const visible = selected === 'all' || card.dataset.category === selected; card.classList.toggle('is-hidden', !visible); if (visible) shown++ }); count.textContent = String(shown).padStart(2, '0') }));
const metricData = window.pricingMetrics;
if (metricData && document.getElementById('pricingChart')) {
 const summary = window.pricingSummary, svg = document.getElementById('pricingChart'), tip = document.getElementById('chartTooltip'), ns = 'http://www.w3.org/2000/svg';
 document.getElementById('medianF1').textContent = (Math.round((summary.medianF1 + 1e-10) * 1000) / 1000).toFixed(3).replace('.', ','); document.getElementById('medianAuc').textContent = (Math.round((summary.medianAuc + 1e-10) * 1000) / 1000).toFixed(3).replace('.', ','); document.getElementById('categoryCount').textContent = summary.count;
 const W = 760, H = 420, L = 60, R = 20, T = 20, B = 48, x0 = .1, x1 = .9, y0 = .4, y1 = .85; svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
 const X = v => L + (v - x0) / (x1 - x0) * (W - L - R), Y = v => T + (y1 - v) / (y1 - y0) * (H - T - B);
 function el(tag, attrs = {}, parent = svg) { const n = document.createElementNS(ns, tag); for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, v); parent.appendChild(n); return n }
 [.4, .5, .6, .7, .8].forEach(v => { el('line', { x1: L, y1: Y(v), x2: W - R, y2: Y(v), class: 'chart-grid-line' }); const t = el('text', { x: L - 10, y: Y(v) + 4, 'text-anchor': 'end', class: 'chart-axis-text' }); t.textContent = v.toFixed(1) });
 [.1, .3, .5, .7, .9].forEach(v => { el('line', { x1: X(v), y1: T, x2: X(v), y2: H - B, class: 'chart-grid-line' }); const t = el('text', { x: X(v), y: H - B + 20, 'text-anchor': 'middle', class: 'chart-axis-text' }); t.textContent = v.toFixed(1) });
 el('line', { x1: X(summary.medianF1), y1: T, x2: X(summary.medianF1), y2: H - B, class: 'chart-median' }); el('line', { x1: L, y1: Y(.5), x2: W - R, y2: Y(.5), class: 'chart-random' });
 const xname = el('text', { x: (L + W - R) / 2, y: H - 7, 'text-anchor': 'middle', class: 'chart-axis-name' }); xname.textContent = 'F1';
 metricData.forEach((d, i) => { const c = el('circle', { cx: X(d.f1), cy: Y(d.auc), r: 5, fill: 'var(--lime)', class: 'chart-point', opacity: .78, tabindex: 0, role: 'img', 'aria-label': `Catégorie anonymisée ${i + 1} : F1 ${d.f1.toFixed(3)}, AUC ${d.auc.toFixed(3)}` }); const show = e => { const rect = svg.getBoundingClientRect(), parent = svg.parentElement.getBoundingClientRect(), px = e.clientX || rect.left + X(d.f1) / W * rect.width, py = e.clientY || rect.top + Y(d.auc) / H * rect.height; tip.innerHTML = `Catégorie ${String(i + 1).padStart(2, '0')}<br>F1&nbsp; ${d.f1.toFixed(3)} · AUC&nbsp; ${d.auc.toFixed(3)}`; tip.style.display = 'block'; tip.style.left = Math.min(parent.width - 150, Math.max(0, px - parent.left + 9)) + 'px'; tip.style.top = Math.max(0, py - parent.top - 43) + 'px' }; c.addEventListener('pointerenter', show); c.addEventListener('pointermove', show); c.addEventListener('pointerleave', () => tip.style.display = 'none'); c.addEventListener('focus', () => show({ clientX: svg.getBoundingClientRect().left + X(d.f1) / W * svg.getBoundingClientRect().width, clientY: svg.getBoundingClientRect().top + Y(d.auc) / H * svg.getBoundingClientRect().height })); c.addEventListener('blur', () => tip.style.display = 'none') });
}

const captureDialog = document.getElementById('captureDialog'); if (captureDialog) { const image = document.getElementById('captureDialogImage'), caption = document.getElementById('captureDialogCaption'); document.querySelectorAll('.capture-open').forEach(button => button.addEventListener('click', () => { image.src = button.dataset.full; image.alt = button.querySelector('img').alt; caption.textContent = button.dataset.caption; captureDialog.showModal() })); captureDialog.addEventListener('click', event => { if (event.target === captureDialog) captureDialog.close() }) }


const marginZones = [...document.querySelectorAll('.margin-quadrant')]; const quadrantTitle = document.getElementById('quadrantTitle'), quadrantSummary = document.getElementById('quadrantSummary'); if (marginZones.length && quadrantTitle && quadrantSummary) { const activateZone = button => { marginZones.forEach(zone => zone.classList.toggle('is-active', zone === button)); quadrantTitle.textContent = button.dataset.name; quadrantSummary.textContent = button.dataset.summary }; marginZones.forEach(button => { button.addEventListener('pointerenter', () => activateZone(button)); button.addEventListener('focus', () => activateZone(button)); button.addEventListener('click', () => activateZone(button)) }) }


// Experience filter: connects technology groups to their relevant case pages.
const experienceFilters=[...document.querySelectorAll('.skill-filter')],experienceCards=[...document.querySelectorAll('.experience-card[data-skills]')],experienceFilterCount=document.getElementById('experienceFilterCount');function applyExperienceFilter(skill){if(!experienceFilters.length)return;experienceFilters.forEach(button=>{const selected=button.dataset.skill===skill;button.classList.toggle('is-selected',selected);button.setAttribute('aria-pressed',String(selected))});let visible=0;experienceCards.forEach(card=>{const show=skill==='all'||card.dataset.skills.split(/\s+/).includes(skill);card.classList.toggle('is-filtered',!show);if(show)visible++});if(experienceFilterCount)experienceFilterCount.textContent=`${visible} expérience${visible>1?'s':''} affichée${visible>1?'s':''}`}experienceFilters.forEach(button=>button.addEventListener('click',()=>applyExperienceFilter(button.dataset.skill)));document.querySelectorAll('[data-skill-map]').forEach(button=>button.addEventListener('click',()=>{applyExperienceFilter(button.dataset.skillMap);const result=document.getElementById('skillMapResult');if(result)result.textContent=`Expériences filtrées : ${button.querySelector('b')?.textContent||button.textContent.trim()}.`;document.getElementById('parcours')?.scrollIntoView({behavior:'smooth',block:'start'})}));

// Interactive, keyboard-accessible career timeline.
const timelineNodes=[...document.querySelectorAll('[data-timeline-node]')],timelinePosition=document.getElementById('timelinePosition');let timelineIndex=Math.max(0,timelineNodes.findIndex(n=>n.classList.contains('is-current')));function setTimeline(i){if(!timelineNodes.length)return;timelineIndex=(i+timelineNodes.length)%timelineNodes.length;timelineNodes.forEach((node,index)=>{node.classList.toggle('is-current',index===timelineIndex);if(index===timelineIndex)node.setAttribute('aria-current','step');else node.removeAttribute('aria-current')});if(timelinePosition)timelinePosition.textContent=`Étape ${timelineIndex+1} sur ${timelineNodes.length}`}document.querySelectorAll('[data-timeline-step]').forEach(button=>button.addEventListener('click',()=>setTimeline(timelineIndex+Number(button.dataset.timelineStep))));timelineNodes.forEach((node,index)=>node.addEventListener('focus',()=>setTimeline(index)));

// Print only the currently open portfolio page.


// Contact form creates a prefilled email in the visitor's own mail application.
document.querySelectorAll('[data-contact-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form),mailto=form.dataset.mailto;const subject=`Portfolio — ${data.get('subject')||'prise de contact'}`;const message=`Nom : ${data.get('name')}\nE-mail : ${data.get('email')}\nSujet : ${data.get('subject')}\n\n${data.get('message')}`;window.location.href=`mailto:${mailto}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`}));

// Illustrative client-position simulator; real acceptance rules remain business-specific.


